spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8088

logging:
  level:
    root: info

hashgenerator:
  batch-size: 100
  threadpool-size: 5
  threadpool-queue-capacity: 100

hash:
  unique-number:
    range: 100
  maxRange: 10000
  batchSize: 1000
  cache:
    poll-timeout: 100 # milliseconds
    size: 10
    min-fill: 20 # percentage

url:
  shortener:
    address: https://sh.com/

async:
  generator-thread-pool:
    settings:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 100
  cache-thread-pool:
    settings:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 100
